# Generated by Django 6.1 on 2026-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='Identificador único do servidor na rede.', max_length=50, unique=True, verbose_name='Nome da Máquina')),
                ('endereco_ip', models.GenericIPAddressField(help_text='Endereço IPv4 ou IPv6 do servidor.', verbose_name='Endereço IP')),
                ('is_ativo', models.BooleanField(default=True, help_text='Indica se o servidor está ativo para monitoramento.', verbose_name='Monitoramento Ativo')),
                ('data_registro', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o servidor foi registrado.', verbose_name='Data de Registro')),
            ],
        ),
    ]
