# Generated by Django 6.1 on 2026-08-13 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
                ('limite_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Teto Orçamentário (R$)')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='RegistroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição do Item/Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('is_impulsivo', models.BooleanField(default=False, help_text='Marque se a compra foi realizada sem planejamento prévio de 24 horas.', verbose_name='Compra Impulsiva?')),
                ('gatilho', models.CharField(choices=[('REDE_SOCIAL', 'Anúncio em Rede Social'), ('E-MAIL_PROMOCIONAL', 'E-mail / Notificação de Promoção'), ('DESCONTO_TEMPORAL', 'Oferta por Tempo Limitado (Cupom/Flash Sale)'), ('NECESSIDADE_REAL', 'Compra Planejada / Necessidade Real')], default='NECESSIDADE_REAL', max_length=30, verbose_name='Gatilho de Consumo')),
                ('data_compra', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Transação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='main.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Registro de Gasto',
                'verbose_name_plural': 'Registros de Gastos',
            },
        ),
    ]
