# Generated by Django 6.1 on 2026-08-20 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrogasto',
            name='categoria',
            field=models.CharField(choices=[('gastos essenciais', 'Gastos Essenciais'), ('Lazer', 'Lazer'), ('Eletrônicos', 'Eletrônicos'), ('Outros', 'Outros')], max_length=50),
        ),
        migrations.AlterModelOptions(
            name='registrogasto',
            options={},
        ),
        migrations.RemoveField(
            model_name='registrogasto',
            name='data_compra',
        ),
        migrations.RemoveField(
            model_name='registrogasto',
            name='gatilho',
        ),
        migrations.RemoveField(
            model_name='registrogasto',
            name='is_impulsivo',
        ),
        migrations.AddField(
            model_name='registrogasto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrogasto',
            name='impulso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrogasto',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registrogasto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
