# Generated by Django 6.1 on 2026-08-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_registrogasto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrogasto',
            name='dias_reflexao',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='registrogasto',
            name='estado',
            field=models.CharField(choices=[('PLANEJADO', 'Planejado / Efetivado'), ('CONGELADO', 'Na Geladeira (Reflexão)'), ('DESISTIDO', 'Compra Abortada (Economizado)')], default='PLANEJADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrogasto',
            name='categoria',
            field=models.CharField(choices=[('essenciais', 'Gastos Essenciais'), ('lazer', 'Lazer'), ('eletronicos', 'Eletrônicos'), ('vestuario', 'Vestuário'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrogasto',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
