# Generated by Django 6.1 on 2026-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_registrogasto_dias_reflexao_registrogasto_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(default='Geral', max_length=100)),
                ('impulso', models.BooleanField(default=False)),
                ('estado', models.CharField(default='PLANEJADO', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroGasto',
        ),
    ]
