# Generated by Django 6.1 on 2026-08-26 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gasto_delete_registrogasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='gasto',
            name='dias_reflexao',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='gasto',
            name='prioridade',
            field=models.CharField(choices=[('ESSENCIAL', 'Essencial'), ('IMPORTANTE', 'Importante'), ('NAO_ESSENCIAL', 'Não Essencial'), ('IMPULSIVO', 'Impulsivo')], default='IMPORTANTE', max_length=20),
        ),
        migrations.AddField(
            model_name='gasto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Alimentação', 'Alimentação'), ('Eletrônicos', 'Eletrônicos'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Vestuário', 'Vestuário'), ('Outros', 'Outros')], default='Outros', max_length=50),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('PLANEJADO', 'Planejado'), ('CONGELADO', 'Geladeira de Compras'), ('DESISTIDO', 'Compra Desistida'), ('COMPRADO', 'Comprado')], default='PLANEJADO', max_length=20),
        ),
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_acumulado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_mensal', models.DecimalField(decimal_places=2, default=2800.0, max_digits=10)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=17.5, max_digits=8)),
                ('limite_orcamento', models.DecimalField(decimal_places=2, default=2800.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
